char* kernel =
"?: HERE CONTEXT @ ;"
"?: CURRENT CONTEXT 1 CELLS + ;"
"?: SOURCE-ID CONTEXT 2 CELLS + @ ;"


"?: IF POSTPONE (?BRANCH) HERE 0 , ; IMMEDIATE"
"?: THEN HERE OVER - SWAP ! ; IMMEDIATE"
"?: ELSE POSTPONE AHEAD SWAP POSTPONE THEN ; IMMEDIATE"
;
